# MPLAB IDE generated this makefile for use with GNU make.
# Project: 009_2_Seven_Segment_Display.mcp
# Date: Wed Jan 24 21:13:43 2024

AS = MPASMWIN.exe
CC = 
LD = mplink.exe
AR = mplib.exe
RM = rm

009_2_Seven_Segment_Display.cof : 009_2_Seven_Segment_Display.o
	$(CC) /p16F877 "009_2_Seven_Segment_Display.o" /u_DEBUG /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /o"009_2_Seven_Segment_Display.cof" /M"009_2_Seven_Segment_Display.map" /W

009_2_Seven_Segment_Display.o : 009_2_Seven_Segment_Display.asm ../../Program\ Files\ (x86)/Microchip/MPASM\ Suite/P16F877.INC
	$(AS) /q /p16F877 "009_2_Seven_Segment_Display.asm" /l"009_2_Seven_Segment_Display.lst" /e"009_2_Seven_Segment_Display.err" /o"009_2_Seven_Segment_Display.o" /d__DEBUG=1

clean : 
	$(CC) "009_2_Seven_Segment_Display.o" "009_2_Seven_Segment_Display.err" "009_2_Seven_Segment_Display.lst" "009_2_Seven_Segment_Display.cof" "009_2_Seven_Segment_Display.hex"

